# Generated by Django 4.2.7 on 2023-11-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='rareapi.PostTag', to='rareapi.tag'),
        ),
    ]
