# Generated by Django 4.2.7 on 2023-11-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rare_user',
            new_name='user',
        ),
    ]
